sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 838f4fad

  upload:
    local-path: D:/Develop/sky-take-out/upload
    url-prefix: http://localhost:8080/upload
